from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')
marker = '<!-- v75.23 — Desktop shell: topbar contínua + sidebar integrada + pesquisa global -->'
if marker in s:
    raise SystemExit('v75.23 already applied')

patch = r'''<!-- v75.23 — Desktop shell: topbar contínua + sidebar integrada + pesquisa global -->
<style id="cuidarbem-v75-23-desktop-shell">
@media (min-width:768px){
  :root{--cb-desktop-sidebar:260px;--cb-desktop-topbar:126px}
  .bottom-nav{width:var(--cb-desktop-sidebar)!important;border-right:1px solid rgba(0,75,61,.08)!important;box-shadow:4px 0 28px rgba(0,55,45,.055)!important;background:rgba(255,255,255,.97)!important}
  .nav-brand{height:var(--cb-desktop-topbar)!important;min-height:var(--cb-desktop-topbar)!important;padding:0 20px!important;margin:0!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:12px!important;border-radius:0!important;background:radial-gradient(circle at 0 0,rgba(255,255,255,.09),transparent 45%),linear-gradient(135deg,#0a6b59 0%,#08725e 54%,#087d66 100%)!important;box-shadow:none!important}
  .nav-brand::after{display:none!important}.nav-brand-icon{width:44px!important;height:44px!important;border-radius:14px!important;background:rgba(255,255,255,.16)!important;box-shadow:inset 0 1px rgba(255,255,255,.16)!important}.nav-brand-text{font-size:18px!important}.nav-brand-sub{font-size:10.5px!important}
  .screen>.header,.screen>.header-sub,#screen-home>.header{min-height:var(--cb-desktop-topbar)!important;height:var(--cb-desktop-topbar)!important;padding:0 38px!important;margin:0!important;border-radius:0!important;display:flex!important;align-items:center!important;position:relative!important;overflow:visible!important;background:radial-gradient(circle at 92% -40%,rgba(255,255,255,.10),transparent 34%),linear-gradient(135deg,#08725e 0%,#087963 55%,#0a8069 100%)!important;box-shadow:0 10px 28px rgba(0,77,63,.14)!important}
  .screen>.header::before,.screen>.header-sub::before{content:''!important;position:absolute!important;inset:0!important;pointer-events:none!important;background:linear-gradient(90deg,rgba(255,255,255,.015),transparent 42%,rgba(255,255,255,.025))!important}.screen>.header::after{display:none!important}
  #screen-home .mobile-topbar-title-row{position:relative!important;z-index:3!important;flex:0 0 250px!important;width:250px!important;display:block!important}#screen-home .header-title{display:none!important}#screen-home .mobile-header-subtitle{display:block!important;color:rgba(255,255,255,.74)!important;font-size:12px!important;line-height:1.25!important;margin-top:4px!important}#screen-home .header-greeting{display:block!important;color:#fff!important;opacity:.95!important;font-size:15px!important;font-weight:800!important;margin:0!important}#screen-home .mobile-bell-btn{display:none!important}
  #screen-home .header>.header-date{margin-left:auto!important;margin-right:16px!important;padding:0!important;border:0!important;white-space:nowrap!important;font-size:12px!important;color:rgba(255,255,255,.88)!important;opacity:1!important}#screen-home .header>div[style*="justify-content:space-between"]{margin:0!important;display:flex!important;align-items:center!important;gap:9px!important;flex:0 0 auto!important}#screen-home .header-patient{margin:0!important;min-height:38px!important;padding:7px 13px!important;background:rgba(255,255,255,.15)!important;border:1px solid rgba(255,255,255,.25)!important}#screen-home .header button[onclick="openSamuMode()"]{min-height:38px!important;margin:0!important}#screen-home .mobile-header-actions,#screen-home #streak-badge,#screen-home #patient-mode-header-badge{display:none!important}
  .header-sub{justify-content:flex-start!important;gap:10px!important}.header-sub-title{position:relative!important;z-index:3!important;width:250px!important;flex:0 0 250px!important;font-size:20px!important;line-height:1.1!important;font-weight:900!important;color:#fff!important;margin:0!important}.header-sub>.header-date{display:none!important}
  .cb-desktop-search{position:absolute;z-index:20;left:50%;top:50%;transform:translate(-50%,-50%);width:min(360px,34vw)}.cb-desktop-search-box{position:relative;height:42px;display:flex;align-items:center;border-radius:13px;background:rgba(255,255,255,.94);border:1px solid rgba(255,255,255,.72);box-shadow:0 5px 16px rgba(0,62,50,.12),inset 0 1px rgba(255,255,255,.7);transition:box-shadow .18s,border-color .18s,background .18s}.cb-desktop-search-box:focus-within{background:#fff;border-color:rgba(196,235,225,.95);box-shadow:0 7px 22px rgba(0,62,50,.16),0 0 0 3px rgba(255,255,255,.10)}.cb-desktop-search-icon{width:39px;flex:0 0 39px;display:flex;align-items:center;justify-content:center;color:#5b7069;pointer-events:none}.cb-desktop-search-icon svg{width:17px;height:17px}.cb-desktop-search-input{flex:1;min-width:0;height:100%;border:0;outline:0;background:transparent;color:#17352d;font-family:'Nunito Sans',sans-serif;font-size:13px;font-weight:600;padding:0 4px 0 0}.cb-desktop-search-input::placeholder{color:#82938d;opacity:1}.cb-desktop-search-clear{width:36px;height:36px;margin-right:3px;border:0;background:transparent;color:#687b75;display:none;align-items:center;justify-content:center;border-radius:9px;cursor:pointer;font-size:18px;line-height:1}.cb-desktop-search-clear.show{display:flex}.cb-desktop-search-clear:hover{background:#eef6f2;color:#0b6d59}
  .cb-desktop-search-results{position:absolute;top:48px;left:0;right:0;display:none;max-height:360px;overflow:auto;padding:7px;border-radius:15px;background:rgba(255,255,255,.985);border:1px solid rgba(12,108,88,.12);box-shadow:0 18px 46px rgba(0,55,45,.19)}.cb-desktop-search-results.open{display:block}.cb-search-empty{padding:14px 12px;color:#6d7e78;font-size:12.5px;text-align:center}.cb-search-result{width:100%;border:0;background:transparent;padding:10px 11px;border-radius:11px;display:flex;gap:10px;align-items:flex-start;text-align:left;cursor:pointer;color:#17352d}.cb-search-result:hover{background:#edf8f3}.cb-search-result-icon{width:28px;height:28px;flex:0 0 28px;border-radius:9px;display:flex;align-items:center;justify-content:center;background:#e7f4ef;font-size:14px}.cb-search-result-title{font-size:13px;font-weight:800;line-height:1.25}.cb-search-result-sub{font-size:11px;color:#6c7e77;margin-top:2px;line-height:1.3}
  #screen-home.active{grid-template-rows:var(--cb-desktop-topbar) minmax(0,1fr)!important}.nav-btn{margin-left:12px!important;margin-right:12px!important;width:calc(100% - 24px)!important;border-radius:12px!important;box-shadow:none!important}.nav-btn.active{box-shadow:0 7px 18px rgba(8,111,91,.18)!important}
}
@media (max-width:767px){.cb-desktop-search{display:none!important}}
</style>
<script id="cuidarbem-v75-23-desktop-shell-js">
(function(){'use strict';
const META=[{id:'home',label:'Início',icon:'⌂',sub:'Resumo e tarefas de hoje'},{id:'calendar',label:'Agenda',icon:'📅',sub:'Rotinas, remédios e compromissos'},{id:'dashboard',label:'Saúde',icon:'♡',sub:'Acompanhamento e evolução'},{id:'ocr',label:'Receita',icon:'📷',sub:'Receitas e leitura por câmera'},{id:'reports',label:'Relatório',icon:'▥',sub:'Histórico e indicadores'},{id:'appt',label:'Consulta',icon:'🗓',sub:'Consultas e exames'},{id:'profile',label:'Perfil',icon:'♙',sub:'Paciente e configurações'}];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function go(id){try{if(typeof window.goScreen==='function')window.goScreen(id);else{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('screen-'+id)?.classList.add('active')}}catch(e){}}
function tasksFor(q){const out=[];try{const list=Array.isArray(window.tasks)?window.tasks:(typeof tasks!=='undefined'&&Array.isArray(tasks)?tasks:[]);list.forEach(t=>{const hay=norm([t.name,t.medName,t.doctor,t.examDoctor,t.local,t.type,t.obs,t.dose].filter(Boolean).join(' '));if(hay.includes(q))out.push({icon:t.type==='med'?'💊':t.type==='cons'?'🩺':t.type==='exam'?'🔬':t.type==='fisio'?'🦾':'✓',title:t.name||t.medName||'Tarefa',sub:[t.date,t.time,t.dose,t.doctor||t.examDoctor,t.local].filter(Boolean).join(' · '),screen:'calendar'})})}catch(e){}return out.slice(0,5)}
function render(root,input){const panel=root.querySelector('.cb-desktop-search-results'),clear=root.querySelector('.cb-desktop-search-clear'),raw=input.value.trim();clear.classList.toggle('show',raw.length>0);if(!raw){panel.classList.remove('open');panel.innerHTML='';return}const q=norm(raw),screens=META.filter(x=>norm(x.label+' '+x.sub).includes(q)).map(x=>({icon:x.icon,title:x.label,sub:x.sub,screen:x.id})),results=[...screens,...tasksFor(q)].slice(0,8);panel.classList.add('open');if(!results.length){panel.innerHTML='<div class="cb-search-empty">Nenhum resultado encontrado.</div>';return}panel.innerHTML=results.map((r,i)=>`<button class="cb-search-result" type="button" data-i="${i}"><span class="cb-search-result-icon">${esc(r.icon)}</span><span><div class="cb-search-result-title">${esc(r.title)}</div><div class="cb-search-result-sub">${esc(r.sub||'')}</div></span></button>`).join('');panel.querySelectorAll('.cb-search-result').forEach((b,i)=>b.addEventListener('click',()=>{go(results[i].screen);panel.classList.remove('open');input.blur()}))}
function make(){const root=document.createElement('div');root.className='cb-desktop-search';root.innerHTML=`<div class="cb-desktop-search-box"><span class="cb-desktop-search-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><circle cx="11" cy="11" r="6.5"></circle><path d="M16 16l4 4"></path></svg></span><input class="cb-desktop-search-input" type="search" autocomplete="off" placeholder="Buscar no CuidarBem..." aria-label="Pesquisa global"><button class="cb-desktop-search-clear" type="button" aria-label="Limpar pesquisa">×</button></div><div class="cb-desktop-search-results" role="listbox"></div>`;const input=root.querySelector('input'),clear=root.querySelector('.cb-desktop-search-clear');input.addEventListener('input',()=>render(root,input));input.addEventListener('focus',()=>{if(input.value.trim())render(root,input)});clear.addEventListener('click',()=>{input.value='';render(root,input);input.focus()});document.addEventListener('pointerdown',e=>{if(!root.contains(e.target))root.querySelector('.cb-desktop-search-results')?.classList.remove('open')});return root}
function mount(){if(document.querySelector('.cb-desktop-search'))return;document.querySelectorAll('.screen > .header, .screen > .header-sub').forEach(h=>h.appendChild(make()));try{localStorage.setItem('cuidarbem_patch_version','v75.23-desktop-topbar-sidebar-global-search')}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();})();
</script>'''

if '</body>' not in s:
    raise SystemExit('missing </body>')
s = s.replace('</body>', patch + '\n</body>', 1)
p.write_text(s, encoding='utf-8')
